baseURL = 'https://prcdkamilly-boop.github.io/'
languageCode = 'zh-tw'
title = '駭客脈動中心'
theme = 'PaperMod'

paginate = 5
enableRobotsTXT = true
summaryLength = 0
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardLineBreak = true

[params]
    DateFormat = "2006/01/02"
    description = "專注於網路安全、滲透測試與數位脈動的技術分享 。"
    keywords = ["駭客", "網路安全", "滲透測試", "HackPulse"]
    author = "HackPulse Central"

    [params.cover]
        responsiveImages = true
        linkFullImages = false
        hiddenInSingle = true 
        hiddenInList = false

    [params.assets]
        favicon = "images/hacker_logo.png"
        disableFingerprinting = true

    [params.homeInfoParams]
        Title = "歡迎來到駭客脈動中心 💻"
        Content = """
專注於網路安全、滲透測試與數位脈動的技術分享。在這裡，我們探索代碼背後的真相。  
  

<a href='https://t.me/HackPulse_Central' target='_blank' style='color: #00ff41; font-size: 1.5rem; font-weight: bold; text-decoration: none; border: 1px solid #00ff41; padding: 10px 20px; display: inline-block; border-radius: 5px;'>
    ⚡ 請聯絡 Telegram: @HackPulse_Central
</a>
"""

    ShowReadingTime = false
    ShowToc = true
    ShowCodeCopyButtons = true
    defaultTheme = "dark"
    disableThemeToggle = true
